[versions]
jvmTarget = "17"
kotlin = "2.3.21"
agp = "9.1.1"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"

version-code = "1"
version-name = "1.0.0"

ksp = "2.3.8"
room = "2.8.4"
aboutLibraries = "14.2.1"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-multiplatform = "org.jetbrains.compose:1.11.0"
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-kmpLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
metro = "dev.zacsweers.metro:1.1.1"
room = { id = "androidx.room", version.ref = "room" }
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }

convention-kmp-application = { id = "convention-kmp-application" }
convention-kmp-library = { id = "convention-kmp-library" }
convention-kmp-compose = { id = "convention-kmp-compose" }

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0"
kotlinx-coroutines-test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.11.0"
kotlinx-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.11.0"
kotlinx-coroutines-swing = "org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.11.0"
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0"
kotlinx-io-byteString = "org.jetbrains.kotlinx:kotlinx-io-bytestring:0.9.0"

compose-foundation = "org.jetbrains.compose.foundation:foundation:1.11.0"
compose-material3 = "org.jetbrains.compose.material3:material3:1.9.0"
compose-resources = "org.jetbrains.compose.components:components-resources:1.11.0"

androidx-activity-compose = "androidx.activity:activity-compose:1.13.0"
androidx-lifecycle-viewModelCompose = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose:2.10.0"
androidx-lifecycle-runtimeCompose = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose:2.10.0"
androidx-startup = "androidx.startup:startup-runtime:1.2.0"

room-runtime = "androidx.room:room-runtime:2.8.4"
room-compiler = "androidx.room:room-compiler:2.8.4"
room-sqliteBundled = "androidx.sqlite:sqlite-bundled:2.6.2"

datastore-core = "androidx.datastore:datastore:1.2.1"
datastore-preferences = "androidx.datastore:datastore-preferences:1.2.1"

metro-viewModelCompose = "dev.zacsweers.metro:metrox-viewmodel-compose:1.1.1"

ktor-core = "io.ktor:ktor-client-core:3.5.0"
ktor-okhttp = "io.ktor:ktor-client-okhttp:3.5.0"
ktor-darwin = "io.ktor:ktor-client-darwin:3.5.0"
ktor-java = "io.ktor:ktor-client-java:3.5.0"
ktor-contentNegotiation = "io.ktor:ktor-client-content-negotiation:3.5.0"
ktor-kotlinxJson = "io.ktor:ktor-serialization-kotlinx-json:3.5.0"
ktor-mock = "io.ktor:ktor-client-mock:3.5.0"

coil-core = "io.coil-kt.coil3:coil-compose:3.4.0"
coil-ktor = "io.coil-kt.coil3:coil-network-ktor3:3.4.0"

navigation = "org.jetbrains.androidx.navigation:navigation-compose:2.9.2"

paths = "me.sujanpoudel.multiplatform.utils:multiplatform-paths:0.2.2"

aboutLibraries-compose = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }
